# 워크플로우 이름
name: ESLint & Build Test

# 이 워크플로우가 실행되는 조건
on:
  pull_request: # PR 발생 시 실행
    branches:
      - main # main 브랜치로 PR 열릴 때 실행
      - develop # develop 브랜치로 PR 열릴 때 실행
  workflow_dispatch: # 수동 실행도 가능하게 함 (GitHub UI에서 실행 버튼 생김)

# 실제 작업 정의
jobs:
  test:
    runs-on: ubuntu-latest # 최신 Ubuntu 환경에서 실행

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        # 현재 레포지토리 코드를 받아옴 (CI 환경에 clone 하는 것과 같음)

      - name: Install NodeJs & Pnpm package manager
        uses: actions/setup-node@v4
        with:
          node-version: 22
        # Node.js 22 버전을 설치 (최신 버전 사용 중)
        # pnpm도 자동 설치됨 (setup-node가 지원함)

      - name: Install Pnpm package manager
        run: |
          npm install -g pnpm
        # 혹시 setup-node에서 자동 설치가 안 될 경우 대비로 pnpm 명시적으로 설치

      - name: Install Dependencies
        run: pnpm install
        # pnpm으로 프로젝트 의존성 설치

      - name: Lint Code
        run: pnpm lint
        # ESLint 검사 실행 (보통 package.json의 "lint" 스크립트가 정의돼 있어야 함)

      - name: Build Test
        run: pnpm run build
        # 프로젝트 빌드 실행 → 컴파일 오류 등 체크
